# Generated by Django 4.0.2 on 2022-03-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'marche',
                'db_table': 'vsb_app_marca',
            },
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=6, unique=True)),
                ('carburante', models.CharField(choices=[('B', 'Benzina'), ('D', 'Gasolio'), ('G', 'GPL'), ('M', 'Metano'), ('E', 'Elettricità')], max_length=1)),
                ('cilindrata', models.IntegerField()),
                ('cavalli', models.IntegerField()),
                ('potenza', models.IntegerField()),
                ('stato', models.CharField(choices=[('N', 'Nuovo'), ('U', 'Usato')], max_length=1)),
                ('km_percorsi', models.IntegerField()),
                ('anno_produzione', models.DateField()),
                ('numero_proprietari', models.IntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsb_app.marca')),
            ],
            options={
                'verbose_name_plural': 'automobili',
                'db_table': 'vsb_app_automobile',
            },
        ),
    ]
