# Generated by Django 4.0.2 on 2022-04-09 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vsb_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=7, unique=True)),
                ('stato', models.CharField(blank=True, choices=[(None, 'Seleziona lo stato'), ('Nuovo', 'Nuovo'), ('Usato', 'Usato')], max_length=100, null=True)),
                ('modello', models.CharField(blank=True, max_length=100, null=True)),
                ('cavalli', models.IntegerField()),
                ('potenza', models.IntegerField()),
                ('alimentazione', models.CharField(blank=True, max_length=100, null=True)),
                ('km_percorsi', models.IntegerField()),
                ('anno_immatricolazione', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), vsb_app.models.max_value_current_year])),
                ('numero_proprietari', models.IntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cambio', models.CharField(blank=True, choices=[(None, 'Seleziona il cambio'), ('Manuale', 'Manuale'), ('Automatico', 'Automatico')], max_length=100, null=True)),
                ('tipologie_di_uso', models.CharField(blank=True, choices=[(None, "Seleziona la tipologia d'uso"), ('Privato', 'Privato'), ('Aziendale', 'Aziendale'), ('Iva esposta', 'Iva esposta')], max_length=100, null=True)),
                ('numero_marce', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('neopatentato', models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Si', 'Si'), ('No', 'No')], max_length=100, null=True)),
                ('consumo', models.CharField(blank=True, max_length=100, null=True)),
                ('classe_emissioni', models.IntegerField(blank=True, null=True)),
                ('colore', models.CharField(blank=True, max_length=100, null=True)),
                ('trazione', models.CharField(blank=True, choices=[(None, 'Seleziona la trazione'), ('Anteriore', 'Anteriore'), ('Posteriore', 'Posteriore'), ('Integrale', 'Integrale')], max_length=100, null=True)),
                ('carrozzeria', models.CharField(blank=True, choices=[(None, 'Seleziona la carrozzeria'), ('Berlina', 'Berlina'), ('Station Wagon', 'Station Wagon'), ('SUV', 'SUV'), ('Coupè', 'Coupè'), ('Cabrio', 'Cabrio')], max_length=100, null=True)),
                ('peso_a_vuoto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2000)])),
                ('porte', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)])),
                ('posti', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('data_registrazione', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'automobili',
                'db_table': 'vsb_app_automobile',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'marche',
                'db_table': 'vsb_app_marca',
            },
        ),
        migrations.CreateModel(
            name='ImmaginiAutomobili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to=vsb_app.models.get_temp_image_path)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='vsb_app.automobile')),
            ],
            options={
                'verbose_name_plural': 'immagini',
                'db_table': 'vsb_app_immaginiAutomobili',
            },
        ),
        migrations.CreateModel(
            name='Concessionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=100, unique=True)),
                ('partita_IVA', models.CharField(max_length=11, unique=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'concessionarie',
                'db_table': 'vsb_app_concessionaria',
            },
        ),
        migrations.AddField(
            model_name='automobile',
            name='concessionaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsb_app.concessionaria'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsb_app.marca'),
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsb_app.automobile')),
            ],
            options={
                'verbose_name_plural': 'ordini',
                'db_table': 'vsb_app_ordine',
                'unique_together': {('data', 'automobile', 'acquirente')},
            },
        ),
    ]
