# Generated by Django 4.0.2 on 2022-03-27 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='data_registrazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
