# Generated by Django 4.0.2 on 2022-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
