# Generated by Django 4.0.2 on 2022-03-20 10:59

import django.core.validators
from django.db import migrations, models
import vsb_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0002_immaginiautomobili'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='modello',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='anno_produzione',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(vsb_app.models.max_value_current_year)]),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='carburante',
            field=models.CharField(choices=[('', 'Seleziona'), ('B', 'Benzina'), ('D', 'Gasolio'), ('G', 'GPL'), ('M', 'Metano'), ('E', 'Elettricità')], max_length=1),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='stato',
            field=models.CharField(choices=[('', 'Seleziona'), ('N', 'Nuovo'), ('U', 'Usato')], max_length=1),
        ),
    ]
