# Generated by Django 4.0.2 on 2022-04-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0002_automobile_is_purchased_customuser_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='concessionaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobile', to='vsb_app.concessionaria'),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='acquirente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordine', to='vsb_app.automobile'),
        ),
    ]
