# Generated by Django 4.0.2 on 2022-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0003_alter_automobile_carburante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='carburante',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Benzina', 'Benzina'), ('Gasolio', 'Gasolio'), ('GPL', 'GPL'), ('Metano', 'Metano'), ('Hybrid', 'Hybrid'), ('Elettrico', 'Elettrico')], max_length=100, null=True),
        ),
    ]
