# Generated by Django 4.0.2 on 2022-03-20 11:19

import django.core.validators
from django.db import migrations, models
import vsb_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0003_automobile_modello_alter_automobile_anno_produzione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='anno_produzione',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), vsb_app.models.max_value_current_year]),
        ),
    ]
