# Generated by Django 4.0.2 on 2022-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0004_alter_automobile_anno_produzione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
