# Generated by Django 4.0.2 on 2022-04-10 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0004_alter_automobile_neopatentato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
