# Generated by Django 4.0.2 on 2022-03-30 14:47

import django.core.validators
from django.db import migrations, models
import vsb_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0004_alter_automobile_carburante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobile',
            name='anno_produzione',
        ),
        migrations.RemoveField(
            model_name='automobile',
            name='carburante',
        ),
        migrations.RemoveField(
            model_name='automobile',
            name='cilindrata',
        ),
        migrations.AddField(
            model_name='automobile',
            name='alimentazione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='anno_immatricolazione',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), vsb_app.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='automobile',
            name='carrozzeria',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Berlina', 'Berlina'), ('Station Wagon', 'Station Wagon'), ('SUV', 'SUV'), ('Coupè', 'Coupè'), ('Cabrio', 'Cabrio')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='classe_emissioni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='colore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='consumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='emissioni_CO2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='neopatentato',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Si', 'Si'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobile',
            name='numero_marce',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='automobile',
            name='peso_a_vuoto',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='automobile',
            name='porte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='automobile',
            name='posti',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='automobile',
            name='tipologie_di_uso',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Privato', 'Privato'), ('Aziendale', 'Aziendale'), ('Iva esposta', 'Iva esposta')], max_length=100, null=True),
        ),
    ]
