# Generated by Django 4.0.2 on 2022-04-10 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0005_alter_ordine_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
