# Generated by Django 4.0.2 on 2022-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0005_remove_automobile_anno_produzione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='cambio',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona il cambio'), ('Manuale', 'Manuale'), ('Automatico', 'Automatico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='carrozzeria',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona la carrozzeria'), ('Berlina', 'Berlina'), ('Station Wagon', 'Station Wagon'), ('SUV', 'SUV'), ('Coupè', 'Coupè'), ('Cabrio', 'Cabrio')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='stato',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona lo stato'), ('Nuovo', 'Nuovo'), ('Usato', 'Usato')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='tipologie_di_uso',
            field=models.CharField(blank=True, choices=[(None, "Seleziona la tipologia d'uso"), ('Privato', 'Privato'), ('Aziendale', 'Aziendale'), ('Iva esposta', 'Iva esposta')], max_length=100, null=True),
        ),
    ]
