# Generated by Django 4.0.2 on 2022-03-20 11:39

from django.db import migrations, models
import vsb_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0005_alter_automobile_prezzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='targa',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='immaginiautomobili',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to=vsb_app.models.get_temp_image_path),
        ),
    ]
