# Generated by Django 4.0.2 on 2022-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0006_alter_automobile_cambio_alter_automobile_carrozzeria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobile',
            name='emissioni_CO2',
        ),
        migrations.AddField(
            model_name='automobile',
            name='trazione',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona la trazione'), ('Anteriore', 'Anteriore'), ('Posteriore', 'Posteriore'), ('Integrale', 'Integrale')], max_length=100, null=True),
        ),
    ]
