# Generated by Django 4.0.2 on 2022-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0007_automobile_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='cambio',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Manuale', 'Manuale'), ('Automatico', 'Automatico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='carburante',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Benzina', 'Benzina'), ('Gasolio', 'Gasolio'), ('GPL', 'GPL'), ('Metano', 'Metano'), ('Elettricità', 'Elettricità')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='stato',
            field=models.CharField(blank=True, choices=[(None, 'Seleziona'), ('Nuovo', 'Nuovo'), ('Usato', 'Usato')], max_length=100, null=True),
        ),
    ]
