# Generated by Django 4.0.2 on 2022-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0007_rename_classe_emissioni_automobile_batteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='batteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
