# Generated by Django 4.0.2 on 2022-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0009_alter_automobile_peso_a_vuoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='km_percorsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
