# Generated by Django 4.0.3 on 2022-04-12 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsb_app', '0010_alter_automobile_km_percorsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
